version: "3.9"
services:
  app:
    build:
      context: ./docker
      dockerfile: DockerfileNextjs
    volumes:
      - ./src/:/usr/src/app
    ports: 
      - 3000:3000
    environment:
      - TZ=Asia/Tokyo
    networks:
      - yamanobo
    command: sh -c "npm install && npm run dev"
    tty: true
  storybook:
    build:
      context: .
      dockerfile: ./docker/DockerfileStorybook
    ports:
      - 6006:6006
    volumes:
      - ./storybook:/usr/src/app
    # command: sh -c "npm install --legacy-peer-deps && npm run storybook"
    # command: sh -c "npm run storybook"
    stdin_open: true
    tty: true
    environment:
      - TZ=Asia/Tokyo
    networks:
      - yamanobo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - yamanobo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - yamanobo

networks:
  yamanobo:
    driver: bridge

volumes:
  postgres:

